[project]
name = "karley-agent-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk>=0.2.16",
    "google-adk>=1.7.0",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
