[project]
name = "a2a-data-agent"
version = "0.1.0"
description = "Sample enterprise data agent." 
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk>=0.2.16",
    "aiohttp",
    "python-dotenv"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
