// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: instruction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeriesOfSteps_ResponseGenerator int32

const (
	// default
	SeriesOfSteps_RESPONSE_GENERATOR_UNSPECIFIED SeriesOfSteps_ResponseGenerator = 0
	SeriesOfSteps_RESPONSE_GENERATOR_CONCAT      SeriesOfSteps_ResponseGenerator = 1
)

// Enum value maps for SeriesOfSteps_ResponseGenerator.
var (
	SeriesOfSteps_ResponseGenerator_name = map[int32]string{
		0: "RESPONSE_GENERATOR_UNSPECIFIED",
		1: "RESPONSE_GENERATOR_CONCAT",
	}
	SeriesOfSteps_ResponseGenerator_value = map[string]int32{
		"RESPONSE_GENERATOR_UNSPECIFIED": 0,
		"RESPONSE_GENERATOR_CONCAT":      1,
	}
)

func (x SeriesOfSteps_ResponseGenerator) Enum() *SeriesOfSteps_ResponseGenerator {
	p := new(SeriesOfSteps_ResponseGenerator)
	*p = x
	return p
}

func (x SeriesOfSteps_ResponseGenerator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeriesOfSteps_ResponseGenerator) Descriptor() protoreflect.EnumDescriptor {
	return file_instruction_proto_enumTypes[0].Descriptor()
}

func (SeriesOfSteps_ResponseGenerator) Type() protoreflect.EnumType {
	return &file_instruction_proto_enumTypes[0]
}

func (x SeriesOfSteps_ResponseGenerator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeriesOfSteps_ResponseGenerator.Descriptor instead.
func (SeriesOfSteps_ResponseGenerator) EnumDescriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{3, 0}
}

type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// what should the "agent" do
	//
	// Types that are valid to be assigned to Step:
	//
	//	*Instruction_CallAgent
	//	*Instruction_ReturnResponse
	//	*Instruction_Steps
	Step          isInstruction_Step `protobuf_oneof:"step"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_instruction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetStep() isInstruction_Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *Instruction) GetCallAgent() *CallAgent {
	if x != nil {
		if x, ok := x.Step.(*Instruction_CallAgent); ok {
			return x.CallAgent
		}
	}
	return nil
}

func (x *Instruction) GetReturnResponse() *ReturnResponse {
	if x != nil {
		if x, ok := x.Step.(*Instruction_ReturnResponse); ok {
			return x.ReturnResponse
		}
	}
	return nil
}

func (x *Instruction) GetSteps() *SeriesOfSteps {
	if x != nil {
		if x, ok := x.Step.(*Instruction_Steps); ok {
			return x.Steps
		}
	}
	return nil
}

type isInstruction_Step interface {
	isInstruction_Step()
}

type Instruction_CallAgent struct {
	CallAgent *CallAgent `protobuf:"bytes,1,opt,name=call_agent,json=callAgent,proto3,oneof"`
}

type Instruction_ReturnResponse struct {
	ReturnResponse *ReturnResponse `protobuf:"bytes,2,opt,name=return_response,json=returnResponse,proto3,oneof"`
}

type Instruction_Steps struct {
	Steps *SeriesOfSteps `protobuf:"bytes,3,opt,name=steps,proto3,oneof"`
}

func (*Instruction_CallAgent) isInstruction_Step() {}

func (*Instruction_ReturnResponse) isInstruction_Step() {}

func (*Instruction_Steps) isInstruction_Step() {}

// gets the agent card from a remote agent, calls it and returns the response
type CallAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// which transport use to get agent card and later call
	Transport string `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	// where to get the agent card from
	AgentCardUri string `protobuf:"bytes,2,opt,name=agent_card_uri,json=agentCardUri,proto3" json:"agent_card_uri,omitempty"`
	// instruction for the called agent
	Instruction *Instruction `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	// whether to use streaming
	Streaming     bool `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAgent) Reset() {
	*x = CallAgent{}
	mi := &file_instruction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAgent) ProtoMessage() {}

func (x *CallAgent) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAgent.ProtoReflect.Descriptor instead.
func (*CallAgent) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{1}
}

func (x *CallAgent) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *CallAgent) GetAgentCardUri() string {
	if x != nil {
		return x.AgentCardUri
	}
	return ""
}

func (x *CallAgent) GetInstruction() *Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *CallAgent) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

// this option just returns a response
type ReturnResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// what to return to the calling agent
	Response      string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnResponse) Reset() {
	*x = ReturnResponse{}
	mi := &file_instruction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnResponse) ProtoMessage() {}

func (x *ReturnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnResponse.ProtoReflect.Descriptor instead.
func (*ReturnResponse) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// executes step series and returns response based on response_generator
type SeriesOfSteps struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	Instructions      []*Instruction                  `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	ResponseGenerator SeriesOfSteps_ResponseGenerator `protobuf:"varint,2,opt,name=response_generator,json=responseGenerator,proto3,enum=itk.SeriesOfSteps_ResponseGenerator" json:"response_generator,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SeriesOfSteps) Reset() {
	*x = SeriesOfSteps{}
	mi := &file_instruction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesOfSteps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesOfSteps) ProtoMessage() {}

func (x *SeriesOfSteps) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesOfSteps.ProtoReflect.Descriptor instead.
func (*SeriesOfSteps) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{3}
}

func (x *SeriesOfSteps) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *SeriesOfSteps) GetResponseGenerator() SeriesOfSteps_ResponseGenerator {
	if x != nil {
		return x.ResponseGenerator
	}
	return SeriesOfSteps_RESPONSE_GENERATOR_UNSPECIFIED
}

var File_instruction_proto protoreflect.FileDescriptor

const file_instruction_proto_rawDesc = "" +
	"\n" +
	"\x11instruction.proto\x12\x03itk\"\xb2\x01\n" +
	"\vInstruction\x12/\n" +
	"\n" +
	"call_agent\x18\x01 \x01(\v2\x0e.itk.CallAgentH\x00R\tcallAgent\x12>\n" +
	"\x0freturn_response\x18\x02 \x01(\v2\x13.itk.ReturnResponseH\x00R\x0ereturnResponse\x12*\n" +
	"\x05steps\x18\x03 \x01(\v2\x12.itk.SeriesOfStepsH\x00R\x05stepsB\x06\n" +
	"\x04step\"\xa1\x01\n" +
	"\tCallAgent\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12$\n" +
	"\x0eagent_card_uri\x18\x02 \x01(\tR\fagentCardUri\x122\n" +
	"\vinstruction\x18\x03 \x01(\v2\x10.itk.InstructionR\vinstruction\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\",\n" +
	"\x0eReturnResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"\xf2\x01\n" +
	"\rSeriesOfSteps\x124\n" +
	"\finstructions\x18\x01 \x03(\v2\x10.itk.InstructionR\finstructions\x12S\n" +
	"\x12response_generator\x18\x02 \x01(\x0e2$.itk.SeriesOfSteps.ResponseGeneratorR\x11responseGenerator\"V\n" +
	"\x11ResponseGenerator\x12\"\n" +
	"\x1eRESPONSE_GENERATOR_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESPONSE_GENERATOR_CONCAT\x10\x01b\x06proto3"

var (
	file_instruction_proto_rawDescOnce sync.Once
	file_instruction_proto_rawDescData []byte
)

func file_instruction_proto_rawDescGZIP() []byte {
	file_instruction_proto_rawDescOnce.Do(func() {
		file_instruction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instruction_proto_rawDesc), len(file_instruction_proto_rawDesc)))
	})
	return file_instruction_proto_rawDescData
}

var file_instruction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instruction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_instruction_proto_goTypes = []any{
	(SeriesOfSteps_ResponseGenerator)(0), // 0: itk.SeriesOfSteps.ResponseGenerator
	(*Instruction)(nil),                  // 1: itk.Instruction
	(*CallAgent)(nil),                    // 2: itk.CallAgent
	(*ReturnResponse)(nil),               // 3: itk.ReturnResponse
	(*SeriesOfSteps)(nil),                // 4: itk.SeriesOfSteps
}
var file_instruction_proto_depIdxs = []int32{
	2, // 0: itk.Instruction.call_agent:type_name -> itk.CallAgent
	3, // 1: itk.Instruction.return_response:type_name -> itk.ReturnResponse
	4, // 2: itk.Instruction.steps:type_name -> itk.SeriesOfSteps
	1, // 3: itk.CallAgent.instruction:type_name -> itk.Instruction
	1, // 4: itk.SeriesOfSteps.instructions:type_name -> itk.Instruction
	0, // 5: itk.SeriesOfSteps.response_generator:type_name -> itk.SeriesOfSteps.ResponseGenerator
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_instruction_proto_init() }
func file_instruction_proto_init() {
	if File_instruction_proto != nil {
		return
	}
	file_instruction_proto_msgTypes[0].OneofWrappers = []any{
		(*Instruction_CallAgent)(nil),
		(*Instruction_ReturnResponse)(nil),
		(*Instruction_Steps)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instruction_proto_rawDesc), len(file_instruction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instruction_proto_goTypes,
		DependencyIndexes: file_instruction_proto_depIdxs,
		EnumInfos:         file_instruction_proto_enumTypes,
		MessageInfos:      file_instruction_proto_msgTypes,
	}.Build()
	File_instruction_proto = out.File
	file_instruction_proto_goTypes = nil
	file_instruction_proto_depIdxs = nil
}
