import pathlib

from typing import Any, Literal, Optional

import httpx

from google.adk.agents import LlmAgent
from google.adk.skills import load_skill_from_dir
from google.adk.tools import skill_toolset
from pydantic import BaseModel, Field


# a generic tool to facilitate outbound http requests by the agent
async def execute_http_request(
    url: str,
    method: str,
    params: Optional[dict[str, Any]] = None,  # noqa: UP045
    headers: Optional[dict[str, Any]] = None,  # noqa: UP045
    body: Optional[dict[str, Any]] = None,  # noqa: UP045
) -> Any:
    """Executes an HTTP request.

    Args:
        url: The full URL to send the request to.
        method: The HTTP method (GET, POST, PUT, DELETE, etc.).
        params: Optional query parameters.
        headers: Optional HTTP headers.
        body: Optional JSON body for the request.
    """
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method=method, url=url, params=params, headers=headers, json=body
        )
        response.raise_for_status()
        if response.content:
            return response.json()
        return None


frankfurter_skill = load_skill_from_dir(
    pathlib.Path(__file__).parent / 'skills' / 'frankfurter'
)

my_skill_toolset = skill_toolset.SkillToolset(skills=[frankfurter_skill])


class AgentResponse(BaseModel):
    """Agent response schema.

    Attributes:
        message: Message generated by the agent as response for user input.
        status: Status of the agent response.
            - completed: if the user's query has been answered
            - input-required: for clarifying questions to the user. Use if additional input is required from the user to answer the query
            - failed: Only if there was an error invoking tools.
    """

    message: str = Field(
        description='Message generated by the agent as response for user input'
    )
    status: Literal['completed', 'input-required', 'failed'] = Field(
        description='Status of the agent response'
    )


root_agent = LlmAgent(
    name='skills_agent',
    model='gemini-3-flash-preview',
    description='Currency Conversion agent',
    instruction=(
        "You are an agent that helps with user's currency conversions. Use available tools to help with the conversion."
        'For currency conversions, do not assume target currencies. If user did not specify the target currency, ask for it.'
    ),
    tools=[my_skill_toolset, execute_http_request],
    output_schema=AgentResponse,
)
